In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Matrix
- Matrix Operation
- Transpose
- Determinant
- Adjoint, Inverse
- Rank
- Eigen Values and Eigen Vectors

In [7]:
# Create a Matrix

a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [8]:
a + 2

array([[3, 4],
       [5, 6]])

In [11]:
a - 2

array([[-1,  0],
       [ 1,  2]])

In [12]:
a * 2

array([[2, 4],
       [6, 8]])

In [13]:
b = np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [16]:
a + b

array([[ 6,  8],
       [10, 12]])

In [17]:
a - b

array([[-4, -4],
       [-4, -4]])

In [18]:
a * b

array([[ 5, 12],
       [21, 32]])

In [19]:
a / b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [15]:
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
# Transpose
a

array([[1, 2],
       [3, 4]])

In [24]:
a.T  # Transpose

array([[1, 3],
       [2, 4]])

In [39]:
d = np.array([[1,2,3],[4,5,6],[7,8,9]])
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
d.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [41]:
# Determinant

np.linalg.det(d)

np.float64(0.0)

In [42]:
# Inverse

np.linalg.inv(d)

LinAlgError: Singular matrix

In [44]:
e = np.array([[10,2,30],[4,50,6],[70,8,90]])
e

array([[10,  2, 30],
       [ 4, 50,  6],
       [70,  8, 90]])

In [46]:
y = np.linalg.inv(e)
y

array([[-0.07494949, -0.0010101 ,  0.02505051],
       [-0.0010101 ,  0.02020202, -0.0010101 ],
       [ 0.05838384, -0.0010101 , -0.00828283]])

In [48]:
y = np.round(y,2)
y

array([[-0.07, -0.  ,  0.03],
       [-0.  ,  0.02, -0.  ],
       [ 0.06, -0.  , -0.01]])

In [49]:
y = np.rint(y).astype(int)
y

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [50]:
# Rank

np.linalg.matrix_rank(a)

np.int64(2)

In [54]:
#Eigen Values and Eigen Vectors

eig_val, eig_vec = np.linalg.eig(a)
eig_val

array([-0.37228132,  5.37228132])

In [55]:
eig_vec

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

In [56]:
eig_val

array([-0.37228132,  5.37228132])