In [1]:
import numpy as np

In [2]:
# Covert list/tuple into array
ar1 = np.array([1,2,3,4,5])
ar1

array([1, 2, 3, 4, 5])

In [3]:
type(ar1)   # Data structure for ar1 --> array

numpy.ndarray

In [4]:
np.array([1,2,3,4,'a'])   # everything will be converted to higher order data types
# U --> uni coded strings

array(['1', '2', '3', '4', 'a'], dtype='<U21')

In [5]:
# bool --> int --> float --> complex --> str

In [6]:
np.array([1,2.4,2,3,4,5,6,7,8])

array([1. , 2.4, 2. , 3. , 4. , 5. , 6. , 7. , 8. ])

In [7]:
list1 = [1,2,3,4,5]
[i**2 for i in list1]

[1, 4, 9, 16, 25]

In [8]:
ar1**2

array([ 1,  4,  9, 16, 25])

In [9]:
np.zeros([3,4]) #[3,4] --> shape parameter
#Generates an array of 3 rows and 4 columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.random.random([3,4]) # shape parameteer
#It creates array of 3 rows and 4 columns filled with random numbers in a rangge of 0 to 1

array([[0.9108809 , 0.57111381, 0.64321416, 0.25624151],
       [0.64867885, 0.36477057, 0.79814179, 0.9606789 ],
       [0.04737161, 0.59874342, 0.67654885, 0.8599728 ]])

In [11]:
np.random.randint(0,10) # for every execution it gives random number in range of 0 to 10

8

### Initiating an Array

In [13]:
np.full([3,4], 10) # shape, value
# Array of 3 rows and 4 columns and with a value of 10

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [14]:
np.full([2,2], 'a')   # U --> Strings in numpy (unicoded strings)

array([['a', 'a'],
       ['a', 'a']], dtype='<U1')

In [15]:
range(0,5)

range(0, 5)

In [16]:
for i in range(0,5):   # End value is not included
    print(i, end = ' ')

0 1 2 3 4 

In [17]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [18]:
list(range(0, 10, 2)) #start, end(not included), step value

[0, 2, 4, 6, 8]

In [19]:
np.arange(0,10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(0,10,2) 

array([0, 2, 4, 6, 8])

In [21]:
np.linspace(0,10,6) # start, end(including), value
# from 0 to 10, including 10, generating 6 numbers with equal difference

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [22]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [23]:
# Analyzing Array

In [24]:
ar1 = np.arange(0,10)
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
ar1.dtype

dtype('int64')

In [26]:
ar1.size  # No. of elements

10

In [27]:
ar1.ndim # No. of Dimensions

1

In [55]:
ar2 = np.arange(1,25)
ar2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [56]:
ar2.size

24

In [57]:
ar2 = ar2.reshape(6,4)
ar2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [58]:
ar2.shape

(6, 4)

In [59]:
ar2.ndim

2

In [60]:
# For reshaping the dimension should be the product of the size of the element

In [61]:
ar2 = ar2.reshape(3,3)   #Gives Error

ValueError: cannot reshape array of size 24 into shape (3,3)

In [62]:
ar3 = ar2.reshape(3,2,4) # 3 subarrays with 2 rows and 4 columns
ar3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [63]:
ar3.ndim

3

In [87]:
ar1 = np.arange(1,25).reshape(6,4)
ar1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [88]:
np.arange(1,25).reshape(6,4).shape

(6, 4)

### Array Mathematics

In [67]:
ar1 = np.array([[10,20],[30,40]])
ar1

array([[10, 20],
       [30, 40]])

In [68]:
np.sum(ar1)

np.int64(100)

In [69]:
np.sum(ar1, axis = 0)

array([40, 60])

In [70]:
np.sum(ar1, axis = 1)

array([30, 70])

In [71]:
print(np.add(20,10))
print(np.subtract(20,10))
print(np.multiply(20,10))
print(np.divide(20,10))

30
10
200
2.0


In [72]:
print(np.log(20))
print(np.sqrt(20))
print(np.exp(20))
print(np.sin(20))

2.995732273553991
4.47213595499958
485165195.4097903
0.9129452507276277


In [73]:
ar1

array([[10, 20],
       [30, 40]])

In [74]:
print(np.min(ar1))

10


In [75]:
print(np.mean(ar1)) #average

25.0


In [76]:
print(np.max(ar1))

40


### Slicing

- Index will start from zero and end value is not included [start: end-1]

- for 2D data [start:end-1, start:end-1]

In [78]:
ar2 = np.arange(1,10)
ar2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
list1 = [1,2,3,4,5,6,7,8,9]
list1
list1[3:7]

[4, 5, 6, 7]

In [92]:
ar1 = np.arange(1,25).reshape(6,4)
ar1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [93]:
ar1[2:5,1:3]

array([[10, 11],
       [14, 15],
       [18, 19]])

In [94]:
# If start value is not mentioned python will take 0 as default
# If end value is not mentioned python executes till last

In [95]:
ar1[2:6, :4]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [96]:
ar1[2:6, 0:]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [97]:
ar1[2:, :]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [98]:
# If the objective is to extract few rows with all the columns
ar1[2:] #If no value for columns mentioned it will extract all the columns

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [99]:
 # If the objective is to extract all the rows with few columns
ar1[:,2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16],
       [19, 20],
       [23, 24]])

In [100]:
ar1[:6]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [103]:
np.where(ar1 == 10) # row and column is used to identify index of any value in array

(array([2]), array([1]))

### Array Manipulation

In [105]:
ar1 = np.array([[10,20],[30,40]])
ar2 = np.array([[50,60],[70,80]])
ar2

array([[50, 60],
       [70, 80]])

In [107]:
 np.concatenate([ar1,ar2], axis = 0) # axis = 0 --> perform concatenate operation on rows
# comine ar1 and ar2 at row level

array([[10, 20, 50, 60],
       [30, 40, 70, 80]])

In [109]:
np.row_stack([ar1,ar2])

C:\Users\karan\AppData\Local\Temp\ipykernel_13812\1180121787.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack([ar1,ar2])


array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [113]:
np.vstack([ar1,ar2]) # Vertical Stack

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [114]:
 np.concatenate([ar1,ar2], axis = 1) # axis = 1 --> perform concatenate operation on column
# comine ar1 and ar2 at column level

array([[10, 20, 50, 60],
       [30, 40, 70, 80]])

In [115]:
np.column_stack([ar1,ar2])

array([[10, 20, 50, 60],
       [30, 40, 70, 80]])

In [116]:
np.hstack([ar1,ar2]) # Horizontal Stack

array([[10, 20, 50, 60],
       [30, 40, 70, 80]])

In [120]:
ar3 = np.hstack([ar1,ar2,ar1])
ar3

array([[10, 20, 50, 60, 10, 20],
       [30, 40, 70, 80, 30, 40]])

In [121]:
np.hsplit(ar3,3) # Split array into 3

[array([[10, 20],
        [30, 40]]),
 array([[50, 60],
        [70, 80]]),
 array([[10, 20],
        [30, 40]])]