In [5]:
# 1. Create a numpy array with numpy.array module and with a data type integer and float

import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([1.2,2.3,3.4,4.5,5.6])
print(a, a.dtype)
print(b, b.dtype)

[1 2 3 4 5] int64
[1.2 2.3 3.4 4.5 5.6] float64


In [24]:
# 2. Create 0D, 1D, 2D, 3D and 4D array respectively and also print their shape and dimensions of the numpy array we created above

arr = np.array(10)
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2],[3,4]])
arr3 = np.array([
    [[1,2],[2,3],[3,4]],
    [[5,6],[6,7],[7,8]]
])
print(arr, arr.ndim)
print(arr1, arr1.ndim)
print(arr2, arr2.ndim)
print(arr3, arr3.ndim)

10 0
[1 2 3 4 5] 1
[[1 2]
 [3 4]] 2
[[[1 2]
  [2 3]
  [3 4]]

 [[5 6]
  [6 7]
  [7 8]]] 3


In [26]:
# 3. Create a 2 * 3 , 3 * 3, 4 * 4 and 3 * 4 Identity matrix using numpy

x = np.eye(2,3)  # Create an Identity Matrix
print(x)

y = np.identity(3)
print(y)

z = np.identity(4)
print(z)

w = np.eye(3,4)
print(w)

[[1. 0. 0.]
 [0. 1. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [29]:
# 4. Create a numpy array with shape 2,5 that has all the elements as zero

zero = np.zeros((2,5), dtype='int32')
print(zero)

[[0 0 0 0 0]
 [0 0 0 0 0]]


In [33]:
# 5. Create a numpy array that has the shape 3,5 and all elements are 5

arrFive = np.full((3,5), 5, dtype='int64') # Create array with uniform elements that are mentioned
print(arrFive)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [45]:
# 6. Create a numpy array with random integers in the range 0 to 100 and sample size should be 25

ran = np.random.randint(0,101, (25))
print(ran)

[21 42 38 59  3  2 89 93 94 65 69 48 58 79 14 29 93 50 75 35 37  7 33 10
 40]


In [47]:
# 7. Create a numpy array with a shape 3X3 that should be having all the elements as 1

arrOne = np.ones((3,3))
print(arrOne)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [53]:
# 8. Create a numy array in the shape 2X3 and with random integers in the range 0 to 100 and reshape the array in 3X2 and print the updated shape of the resultant array

arrX = np.random.randint(1,100, (2,3))
print(arrX)
arrxReshape = arrX.reshape(3,2)
print(arrxReshape)
print(f'The shape of the new Array is: {arrxReshape.shape}')

[[41 64 33]
 [72 23 21]]
[[41 64]
 [33 72]
 [23 21]]
The shape of the new Array is: (3, 2)


In [54]:
# 9. Create a random array witht the range 0 to 1000 with size 50

arra = np.random.randint(0,1001, (50))
print(arra)

[921 373 132 286 746 648 592 709  70 348 489 572 909 953 814 812 889 574
 305  67 639 105  76 900 675 445 676 721 501 607 561 386  41 552 149 739
 926 169 325 777 992 993 143 348 701 593 600 840 131  11]


In [57]:
# 10. Print the 1st 10 elements of the array

print(f'First 10 elements are: {arra[:10]}')

First 10 elements are: [921 373 132 286 746 648 592 709  70 348]


In [69]:
# 11. Print the last 10 elements of the array

print(f'Last 10 elements are: {arra[-10:]}')

Last 10 elements are: [992 993 143 348 701 593 600 840 131  11]


In [65]:
# 12. Print elements from 10 to 25

print(arra[10:26])

[489 572 909 953 814 812 889 574 305  67 639 105  76 900 675 445]


In [67]:
# 13. To get the 22nd element

print(arra[22])

76


In [95]:
# 14. Given a numpy array [1,2,3,4,5]
an = np.array([1,2,3,4,5])
print(an)

# Insert 6 at the end of the array
an = np.append(an, 6)
print(an)

# Insert 10 at the beginning
an = np.insert(an, 0, 10)
print(an)

# Insert the element 30 before 4
an = np.insert(an, 4, 30)
print(an)

# Update the element 5 as 50

an[an==5]=50
print(an)

#Delete the element 50 in the updated array
an = np.delete(an, np.where(an==50))
print(an)

[1 2 3 4 5]
[1 2 3 4 5 6]
[10  1  2  3  4  5  6]
[10  1  2  3 30  4  5  6]
[10  1  2  3 30  4 50  6]
[10  1  2  3 30  4  6]


In [100]:
# 15. Sort the arry in ascending and descending order

arrQ = np.array([8,1,5,67,3,55,76,11])
arrsort = np.sort(arrQ)  # Sorts in Ascending Order
arrsortD = np.sort(arrQ)[::-1] # Sorts in Descending Order
print(f'Ascending Order: {arrsort}')
print(f'Descending Order: {arrsortD}')

Ascending Order: [ 1  3  5  8 11 55 67 76]
Descending ORDER: [76 67 55 11  8  5  3  1]
